<?php
/**
 * Implementation of hook_form_alter
 */
function sas_document_viewer_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $fdorm_state, $form_id) {
    if($form_id == 'comment_comment_form') {
        $form['actions']['submit']['#value'] = t('Comment');
    }
}

function sas_document_viewer_page_attachments(array &$attachments) {
    $attachments['#attached']['library'][] = 'sas_document_viewer/global-scripts';
}
