<?php
/**
 * Attach drupalSettings
 */
function sas_document_viewer_preprocess_node(&$variables) {
    $variables['content']['#attached']['drupalSettings']['sasDocumentViewer']['testSetting'] = 'Hello Setting';
}

/**
 * Attach css to admin settings page
 */
function sas_document_viewer_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    if ($form_id == "sas_document_viewer_admin_settings"){
        $form['#attached']['library'][] = 'sas_document_viewer/form-styles';
    }
}
