#Schema for the configuration file sas_document_viewer
sas_document_viewer.settings:
  type: config_object
  label: 'SAS Document Viewer Content Type Settings'
  mapping:
    allowed_types:
      type: sequence
      label: 'Content types SAS Document Viewer can display on'
      sequence:
        type: string
        label: 'Content type'